### ISSUE TITLE
Installationsanleitung MikTex Portable

### ISSUE THREAD

**Issue by bebro** [tudadesign/tudadesign.github.io#12]
Auf Fremdrechnern sind üblicherweise keine Administratorrechte verfügbar.
Hier wird zusätzlich noch die Ausführung von Skripten verhindert.

miktex portable funktioniert trotzdem (Windows 7), daher sollte eine Installationsanleitung dafür verfasst werden.

**Comment by domexy** [comment]
Denkst du bei Fremdrechnern an Institutsrechner?

**Comment by bebro** [comment]
Mehr noch an Rechner in Firmen, z.B. bei externen Abschlussarbeiten.
Installation habe ich eben durchgeführt, d.h. ich übernehme die Anleitung

**Comment by bebro** [comment]
Mit 09c46b925b619ad10f381d00793ff2342186a4c4 behoben

**Comment by bebro** [comment]
fix ist im master

**Comment by bebro** [comment]
Allerdings ist die Anleitung nicht in der Navigation oder Sitemap verlinkt

**Comment by domexy** [comment]
Da die Anleitung nicht sonderlich lang zu sein scheint, könnte es sich anbieten, diese als unterpunkt in die Anleitung von MikTeX mit aufzunehmen.

**Comment by bebro** [comment]
Da das vorgehen nicht wirklich vergleichbar ist, sehe ich da weniger Vorteile von.
